= How to contribute to the CTI project

NOTE: This documentation website and the associated material are free under the https://github.com/LabVIEWCommunityTraining/cti-documentation/blob/main/LICENSE[MIT license].

== Contributing to the documentation

There are multiple ways to contribute to the documentation.

* Adding content
* Translate existing content
* Improve content by fixing typos, spelling, formatting…

=== How to edit a page

To edit the page content do the following thing:

IMPORTANT: To edit content you need to have a https://github.com/[GitHub] account.

* Go to the page to edit
* Click on the `Edit this Page` link at the top right of the page
* Edit the file
* Click the `Commit changes`
* Click `Propose changes` after filling Commit message and Extended description
* Click `Create pull request`

[TIP]
====
The content is written using the https://asciidoc.org/[AsciiDoc] markup language.

To learn the basics and advanced features of this language, visit the https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[AsciiDoc documentation website].
====

== Writing conventions

=== VI names

Use https://docs.asciidoctor.org/asciidoc/latest/text/bold/[bold] style to write VI names.

.VI names
[source#vi-names-code]
[source,asciidoc]
----
Start with placing the *Initialize.vi*, and the *Close.vi* on a new Block Diagram.
----

The <<vi-names-code>> is rendered below.

====
Start with placing the *Initialize.vi*, and the *Close.vi* on a new Block Diagram.
====

=== Menu item path

Use the https://docs.asciidoctor.org/asciidoc/latest/macros/ui-macros/#menu-macro-syntax[Menu macro] to display how to select an item in a menu.

.Menu item path
[source#menu-item-path-code]
[source,asciidoc]
----
Open the start-up menu and click on menu:Other[Visit LabVIEW Community Training on GitHub].
Go to the LabVIEW menu menu:Tools[Advanced > Masscompile].
----

The <<menu-item-path-code>> is rendered below.

====
Open the start-up menu and click on menu:Other[Visit LabVIEW Community Training on GitHub]. +
Go to the LabVIEW menu menu:Tools[Advanced > Masscompile].
====

=== Keyboard shortcut

Use the https://docs.asciidoctor.org/asciidoc/latest/macros/ui-macros/#button-macro-syntax[button macro] syntax to display keystroks used for keyboard shortcuts.

.Keyboard Shortcut
[source#kbd-shortcut-code]
[source,asciidoc]
----
Press kbd:[Ctrl-H] to bring up the context help window.
----

The <<kbd-shortcut-code>> is rendered below.

====
Press kbd:[Ctrl-H] to bring up the context help window.
====

== Asciidoc Syntax tips and tricks

=== Inserting a Youtube video

.YouTube video integration
[source#video]
[source,asciidoc]
----
video::mFiS5q8AXyg[youtube]
----

The <<video>> is rendered below.

====
video::mFiS5q8AXyg[youtube]
====
